window.CLOZE_BANK = [
{id:"c001",q:"The campaign aims to ___ awareness of the problem.",o:["raise","lift","rise","grow"],a:0,t:"Collocation",why:"La colocación es raise awareness."},
{id:"c002",q:"We finally ___ an agreement after two hours.",o:["reached","arrived","achieved","met"],a:0,t:"Collocation",why:"Se dice reach an agreement."},
{id:"c003",q:"The hotel failed to ___ our expectations.",o:["meet","reach","fill","complete"],a:0,t:"Collocation",why:"La colocación es meet expectations."},
{id:"c004",q:"Please ___ in mind that prices may change.",o:["bear","hold","keep","carry"],a:0,t:"Collocation",why:"La expresión fija es bear in mind."},
{id:"c005",q:"She has made rapid ___ since starting the course.",o:["progress","advance","improvement","development"],a:0,t:"Collocation",why:"Make progress es la combinación natural."},
{id:"c006",q:"The article ___ attention to a serious issue.",o:["draws","pulls","takes","brings"],a:0,t:"Collocation",why:"Se dice draw attention to something."},
{id:"c007",q:"You should take ___ of the free trial.",o:["advantage","benefit","profit","chance"],a:0,t:"Collocation",why:"La expresión es take advantage of."},
{id:"c008",q:"The new rules ___ a serious challenge for small firms.",o:["pose","put","place","make"],a:0,t:"Collocation",why:"Pose a challenge/threat/problem es una colocación típica."},
{id:"c009",q:"It's hard to keep ___ of all these passwords.",o:["track","trace","record","pace"],a:0,t:"Collocation",why:"Keep track of significa seguir/controlar."},
{id:"c010",q:"You need to pay close ___ to the instructions.",o:["attention","notice","care","interest"],a:0,t:"Collocation",why:"Pay attention to es la combinación fija."},
{id:"c011",q:"He gained valuable ___ while working abroad.",o:["experience","practice","knowledge","skill"],a:0,t:"Collocation",why:"Gain experience es la colocación natural."},
{id:"c012",q:"The committee will ___ a meeting next Monday.",o:["hold","make","do","take"],a:0,t:"Collocation",why:"Se dice hold a meeting."},
{id:"c013",q:"Parents should ___ a good example for their children.",o:["set","put","make","give"],a:0,t:"Collocation",why:"Set an example es la expresión correcta."},
{id:"c014",q:"There is a strong ___ that the event will be cancelled.",o:["possibility","opportunity","occasion","ability"],a:0,t:"Collocation",why:"Strong possibility es una colocación muy frecuente."},
{id:"c015",q:"The two problems are closely ___ to each other.",o:["related","joined","linked up","connected with"],a:0,t:"Collocation",why:"Closely related to es la combinación esperada."},
{id:"c016",q:"She was deeply ___ about the test results.",o:["concerned","worriedly","affected","serious"],a:0,t:"Collocation",why:"Deeply concerned es una colocación habitual."},
{id:"c017",q:"Tickets are now widely ___ online.",o:["available","possible","open","free"],a:0,t:"Collocation",why:"Widely available es la combinación natural."},
{id:"c018",q:"The company has ___ responsibility for the mistake.",o:["accepted","taken up","received","admitted"],a:0,t:"Collocation",why:"Accept responsibility es la colocación correcta."},
{id:"c019",q:"We came to the ___ that the plan was too expensive.",o:["conclusion","decision","result","answer"],a:0,t:"Collocation",why:"Come to the conclusion es una expresión fija."},
{id:"c020",q:"The new software has had a major ___ on productivity.",o:["impact","result","cause","change"],a:0,t:"Collocation",why:"Have an impact on es la combinación correcta."},
{id:"p001",q:"She is capable ___ working under pressure.",o:["of","to","for","with"],a:0,t:"Preposition",why:"Capable va seguido de of + -ing."},
{id:"p002",q:"Who is responsible ___ booking the room?",o:["for","of","to","with"],a:0,t:"Preposition",why:"Responsible for + noun/-ing."},
{id:"p003",q:"He insisted ___ paying for dinner.",o:["on","in","at","for"],a:0,t:"Preposition",why:"Insist on + -ing."},
{id:"p004",q:"I object ___ being treated like that.",o:["to","for","at","on"],a:0,t:"Preposition",why:"Object to + noun/-ing."},
{id:"p005",q:"She succeeded ___ finding a cheaper flight.",o:["in","at","on","with"],a:0,t:"Preposition",why:"Succeed in + -ing."},
{id:"p006",q:"Nothing could prevent him ___ applying again.",o:["from","of","to","against"],a:0,t:"Preposition",why:"Prevent someone from + -ing."},
{id:"p007",q:"They accused him ___ breaking the rules.",o:["of","for","with","from"],a:0,t:"Preposition",why:"Accuse someone of + -ing."},
{id:"p008",q:"I apologised ___ arriving so late.",o:["for","of","about","to"],a:0,t:"Preposition",why:"Apologise for + noun/-ing."},
{id:"p009",q:"Many students rely ___ public transport.",o:["on","in","at","for"],a:0,t:"Preposition",why:"Rely on es la combinación correcta."},
{id:"p010",q:"Do you approve ___ the new proposal?",o:["of","to","for","with"],a:0,t:"Preposition",why:"Approve of + noun/-ing."},
{id:"p011",q:"Are you familiar ___ this type of software?",o:["with","to","of","about"],a:0,t:"Preposition",why:"Familiar with es la combinación correcta."},
{id:"p012",q:"Your answer is very similar ___ mine.",o:["to","with","as","of"],a:0,t:"Preposition",why:"Similar to, no similar with."},
{id:"p013",q:"I wasn't aware ___ the change in schedule.",o:["of","about","for","to"],a:0,t:"Preposition",why:"Aware of + noun."},
{id:"p014",q:"She is involved ___ several local projects.",o:["in","with","at","on"],a:0,t:"Preposition",why:"Be involved in + activity/project."},
{id:"p015",q:"Everyone can benefit ___ regular exercise.",o:["from","of","with","by"],a:0,t:"Preposition",why:"Benefit from something."},
{id:"p016",q:"The course consists ___ six short modules.",o:["of","in","from","with"],a:0,t:"Preposition",why:"Consist of = estar compuesto de."},
{id:"p017",q:"Tourism contributes ___ the local economy.",o:["to","for","with","in"],a:0,t:"Preposition",why:"Contribute to something."},
{id:"p018",q:"How do you cope ___ so much work?",o:["with","to","for","against"],a:0,t:"Preposition",why:"Cope with = hacer frente a."},
{id:"p019",q:"It took weeks to recover ___ the illness.",o:["from","of","with","after"],a:0,t:"Preposition",why:"Recover from an illness/problem."},
{id:"p020",q:"Try to concentrate ___ what you're doing.",o:["on","in","at","to"],a:0,t:"Preposition",why:"Concentrate on something."},
{id:"v001",q:"The scientists will ___ out further tests.",o:["carry","make","take","bring"],a:0,t:"Phrasal verb",why:"Carry out tests/research = realizar."},
{id:"v002",q:"I came ___ an old photo while cleaning.",o:["across","over","through","by"],a:0,t:"Phrasal verb",why:"Come across = encontrar por casualidad."},
{id:"v003",q:"We need to find ___ what caused the error.",o:["out","up","off","over"],a:0,t:"Phrasal verb",why:"Find out = averiguar."},
{id:"v004",q:"The police are looking ___ the complaint.",o:["into","after","over","for"],a:0,t:"Phrasal verb",why:"Look into = investigar."},
{id:"v005",q:"Don't put ___ making the appointment.",o:["off","out","away","down"],a:0,t:"Phrasal verb",why:"Put off = aplazar."},
{id:"v006",q:"We've run ___ milk again.",o:["out of","away from","off with","down on"],a:0,t:"Phrasal verb",why:"Run out of = quedarse sin."},
{id:"v007",q:"They plan to set ___ a new business.",o:["up","out","off","on"],a:0,t:"Phrasal verb",why:"Set up a business = montar/crear."},
{id:"v008",q:"A larger company may take ___ the firm.",o:["over","up","off","out"],a:0,t:"Phrasal verb",why:"Take over = asumir el control."},
{id:"v009",q:"She turned ___ the job because of the salary.",o:["down","off","out","away"],a:0,t:"Phrasal verb",why:"Turn down an offer/job = rechazar."},
{id:"v010",q:"Can you work ___ the total cost?",o:["out","up","over","off"],a:0,t:"Phrasal verb",why:"Work out = calcular/resolver."},
{id:"v011",q:"Why did you bring ___ that subject?",o:["up","out","on","over"],a:0,t:"Phrasal verb",why:"Bring up a subject = sacar un tema."},
{id:"v012",q:"The match was called ___ because of rain.",o:["off","out","away","down"],a:0,t:"Phrasal verb",why:"Call off = cancelar."},
{id:"v013",q:"We need to come ___ with a better idea.",o:["up","out","over","through"],a:0,t:"Phrasal verb",why:"Come up with = idear."},
{id:"v014",q:"It took him months to get ___ the disappointment.",o:["over","through","off","away"],a:0,t:"Phrasal verb",why:"Get over = superar/recuperarse."},
{id:"v015",q:"I can't keep ___ with all these updates.",o:["up","on","out","over"],a:0,t:"Phrasal verb",why:"Keep up with = mantenerse al día."},
{id:"v016",q:"I'm looking forward ___ seeing you.",o:["to","for","at","on"],a:0,t:"Phrasal verb",why:"Look forward to + -ing."},
{id:"v017",q:"I won't put ___ with this noise any longer.",o:["up","out","on","off"],a:0,t:"Phrasal verb",why:"Put up with = soportar."},
{id:"v018",q:"She took ___ photography last year.",o:["up","on","over","out"],a:0,t:"Phrasal verb",why:"Take up an activity = empezar una afición."},
{id:"v019",q:"The exam turned ___ to be easier than expected.",o:["out","up","over","off"],a:0,t:"Phrasal verb",why:"Turn out to be = resultar ser."},
{id:"v020",q:"Please hand ___ your assignment by Friday.",o:["in","out","over","up"],a:0,t:"Phrasal verb",why:"Hand in = entregar."},
{id:"n001",q:"There was a large ___ of people outside.",o:["number","amount","quantity","sum"],a:0,t:"Near synonyms",why:"Number se usa con nombres contables plurales."},
{id:"n002",q:"We only have a small ___ of time left.",o:["amount","number","total","level"],a:0,t:"Near synonyms",why:"Amount se usa con nombres incontables como time."},
{id:"n003",q:"This could be a good ___ to practise your English.",o:["opportunity","occasion","possibility","event"],a:0,t:"Near synonyms",why:"Opportunity = oportunidad para hacer algo."},
{id:"n004",q:"Please ___ me what happened.",o:["tell","say","speak","talk"],a:0,t:"Near synonyms",why:"Tell va directamente con persona: tell me."},
{id:"n005",q:"This photo ___ me of our trip to Rome.",o:["reminds","remembers","recalls","recognises"],a:0,t:"Near synonyms",why:"Remind someone of something."},
{id:"n006",q:"She finally ___ her goal of running a marathon.",o:["achieved","reached to","arrived","won"],a:0,t:"Near synonyms",why:"Achieve a goal = alcanzar un objetivo."},
{id:"n007",q:"We need to find a practical ___ to the problem.",o:["solution","reply","result","outcome"],a:0,t:"Near synonyms",why:"Solution to a problem es la combinación natural."},
{id:"n008",q:"The conference is the biggest ___ of the year.",o:["event","incident","case","situation"],a:0,t:"Near synonyms",why:"Event se refiere a un acontecimiento organizado."},
{id:"n009",q:"The train ___ took almost six hours.",o:["journey","travel","trip","tour"],a:0,t:"Near synonyms",why:"Journey = trayecto concreto de un lugar a otro."},
{id:"n010",q:"Can I ___ your pen for a minute?",o:["borrow","lend","hire","rent"],a:0,t:"Near synonyms",why:"Borrow = tomar prestado; lend = prestar."},
{id:"n011",q:"He felt ___ after moving to a new city.",o:["lonely","single","only","unique"],a:0,t:"Near synonyms",why:"Lonely expresa sentimiento de soledad."},
{id:"n012",q:"Could you give me some ___ on which course to choose?",o:["advice","advise","notice","warning"],a:0,t:"Near synonyms",why:"Advice es nombre incontable; advise es verbo."},
{id:"n013",q:"It would be ___ to book in advance.",o:["sensible","sensitive","serious","aware"],a:0,t:"Near synonyms",why:"Sensible = sensato; sensitive = sensible/emocional."},
{id:"n014",q:"I suddenly ___ that I'd left my keys at home.",o:["realised","discovered","recognised","noticed to"],a:0,t:"Near synonyms",why:"Realise = darse cuenta de un hecho."},
{id:"n015",q:"Prices are expected to ___ next month.",o:["rise","raise","lift","arise"],a:0,t:"Near synonyms",why:"Rise es intransitivo; raise necesita objeto."},
{id:"n016",q:"We left early to ___ the traffic.",o:["avoid","prevent","protect","ignore"],a:0,t:"Near synonyms",why:"Avoid + noun/-ing = evitar."},
{id:"n017",q:"The rules don't ___ visitors to take photos.",o:["allow","let","accept","agree"],a:0,t:"Near synonyms",why:"Allow someone to do; let someone do sin to."},
{id:"n018",q:"Lack of sleep can ___ your concentration.",o:["affect","effect","result","cause to"],a:0,t:"Near synonyms",why:"Affect es verbo; effect suele ser nombre."},
{id:"n019",q:"The job ___ good communication skills.",o:["requires","requests","demands for","claims"],a:0,t:"Near synonyms",why:"Require = necesitar/exigir como requisito."},
{id:"n020",q:"More than 200 people ___ the workshop.",o:["attended","assisted","visited to","took"],a:0,t:"Near synonyms",why:"Attend = asistir a; assist = ayudar."},
{id:"f001",q:"I deleted the file by ___.",o:["accident","purpose","chance of","mistake from"],a:0,t:"Fixed expression",why:"By accident = accidentalmente."},
{id:"f002",q:"She did it on ___, not by mistake.",o:["purpose","reason","intention","aim"],a:0,t:"Fixed expression",why:"On purpose = a propósito."},
{id:"f003",q:"You need to book at least a week in ___.",o:["advance","front","before","ahead of"],a:0,t:"Fixed expression",why:"In advance = con antelación."},
{id:"f004",q:"At ___, I found the course quite difficult.",o:["first","beginning","start","once"],a:0,t:"Fixed expression",why:"At first = al principio."},
{id:"f005",q:"Who's in ___ of organising the event?",o:["charge","responsibility","care","duty"],a:0,t:"Fixed expression",why:"In charge of = encargado de."},
{id:"f006",q:"We went out in ___ of the heavy rain.",o:["spite","case","front","place"],a:0,t:"Fixed expression",why:"In spite of = a pesar de."},
{id:"f007",q:"The flight was delayed. As a ___, we missed the train.",o:["result","reason","cause","consequence of"],a:0,t:"Fixed expression",why:"As a result = como resultado."},
{id:"f008",q:"Take an umbrella in ___ it rains.",o:["case","event","condition","fact"],a:0,t:"Fixed expression",why:"In case + clause = por si."},
{id:"f009",q:"On ___, students spend two hours on the task.",o:["average","mean","general","normal"],a:0,t:"Fixed expression",why:"On average = de media."},
{id:"f010",q:"It will take at ___ three days.",o:["least","less","last","minimum"],a:0,t:"Fixed expression",why:"At least = como mínimo."},
{id:"f011",q:"This is by ___ the best option.",o:["far","much","long","way"],a:0,t:"Fixed expression",why:"By far + superlativo = con diferencia."},
{id:"f012",q:"The two brothers have a lot in ___.",o:["common","same","together","similar"],a:0,t:"Fixed expression",why:"Have something in common."},
{id:"f013",q:"In ___, the course is very practical.",o:["general","whole","total","usual"],a:0,t:"Fixed expression",why:"In general = en general."},
{id:"f014",q:"I enjoyed the trip, and the food in ___.",o:["particular","special","detail","specific"],a:0,t:"Fixed expression",why:"In particular = en particular."},
{id:"f015",q:"I'm writing on ___ of the whole team.",o:["behalf","part","side","name"],a:0,t:"Fixed expression",why:"On behalf of = en nombre de."},
{id:"f016",q:"He works well even under ___.",o:["pressure","stressful","difficulty","force"],a:0,t:"Fixed expression",why:"Under pressure es una expresión fija."},
{id:"f017",q:"This information is already out of ___.",o:["date","time","age","period"],a:0,t:"Fixed expression",why:"Out of date = desactualizado."},
{id:"f018",q:"It may save money in the long ___.",o:["run","term","way","future"],a:0,t:"Fixed expression",why:"In the long run = a largo plazo."},
{id:"f019",q:"Several species are at ___ of disappearing.",o:["risk","danger","chance","threat"],a:0,t:"Fixed expression",why:"At risk of + -ing."},
{id:"f020",q:"For once, the train arrived on ___.",o:["time","hour","period","moment"],a:0,t:"Fixed expression",why:"On time = puntual; in time = con tiempo suficiente."},
{id:"g001",q:"The doctor advised me ___ more exercise.",o:["to take","taking","take","to taking"],a:0,t:"Verb pattern",why:"Advise someone to do something."},
{id:"g002",q:"She suggested ___ a taxi.",o:["taking","to take","take","us to take"],a:0,t:"Verb pattern",why:"Suggest + -ing; no suggest to do."},
{id:"g003",q:"Try to avoid ___ the same mistake.",o:["making","to make","make","made"],a:0,t:"Verb pattern",why:"Avoid + -ing."},
{id:"g004",q:"He managed ___ the work on time.",o:["to finish","finishing","finish","to finishing"],a:0,t:"Verb pattern",why:"Manage to do something."},
{id:"g005",q:"My parents let me ___ out late.",o:["stay","to stay","staying","stayed"],a:0,t:"Verb pattern",why:"Let + object + infinitivo sin to."},
{id:"g006",q:"The film made me ___ differently about the issue.",o:["think","to think","thinking","thought"],a:0,t:"Verb pattern",why:"Make + object + infinitivo sin to."},
{id:"g007",q:"The teacher encouraged us ___ again.",o:["to try","trying","try","to trying"],a:0,t:"Verb pattern",why:"Encourage someone to do."},
{id:"g008",q:"He refused ___ the document.",o:["to sign","signing","sign","to signing"],a:0,t:"Verb pattern",why:"Refuse to do."},
{id:"g009",q:"Have you considered ___ abroad?",o:["working","to work","work","worked"],a:0,t:"Verb pattern",why:"Consider + -ing."},
{id:"g010",q:"I can't afford ___ a new laptop.",o:["to buy","buying","buy","to buying"],a:0,t:"Verb pattern",why:"Afford to do."},
{id:"g011",q:"She admitted ___ the email.",o:["deleting","to delete","delete","deleted"],a:0,t:"Verb pattern",why:"Admit + -ing."},
{id:"g012",q:"He denied ___ the money.",o:["taking","to take","take","took"],a:0,t:"Verb pattern",why:"Deny + -ing."},
{id:"g013",q:"We expect them ___ before six.",o:["to arrive","arriving","arrive","to arriving"],a:0,t:"Verb pattern",why:"Expect someone to do."},
{id:"g014",q:"Remind me ___ Sara tomorrow.",o:["to call","calling","call","to calling"],a:0,t:"Verb pattern",why:"Remind someone to do."},
{id:"g015",q:"She spent all morning ___ for the test.",o:["studying","to study","study","studied"],a:0,t:"Verb pattern",why:"Spend time + -ing."},
{id:"g016",q:"I had difficulty ___ the instructions.",o:["understanding","to understand","understand","understood"],a:0,t:"Verb pattern",why:"Have difficulty + -ing."},
{id:"g017",q:"I'm used to ___ up early.",o:["getting","get","to get","got"],a:0,t:"Verb pattern",why:"Be used to + -ing."},
{id:"g018",q:"We look forward to ___ from you.",o:["hearing","hear","to hear","heard"],a:0,t:"Verb pattern",why:"Look forward to + -ing."},
{id:"g019",q:"I'd rather ___ at home tonight.",o:["stay","to stay","staying","stayed"],a:0,t:"Verb pattern",why:"Would rather + infinitivo sin to."},
{id:"g020",q:"She prefers walking ___ taking the bus.",o:["to","than","from","over than"],a:0,t:"Verb pattern",why:"Prefer X to Y."},
];
Object.freeze(window.CLOZE_BANK);
